[package]
name = "untitled"
version = "0.1.2"
authors = ["SvobodaGaming <medmish6@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
read_input = "0.8"